name : secret-check
on : 
  push :
jobs :
  secret-check:
    runs-on : ubuntu-latest
    steps :
      - name : call the api
        env :
          APP_TOKEN : ${{ secrets.APP_TOKEN }}
        run : |
          if [ -n "$APP_TOKEN" ]; then
          echo "token is available to this step"
          fi
